CREATE TABLE student (ID BIGINT NOT NULL, EMAIL VARCHAR(255), HOLD TINYINT(1) default 0, MAJOR VARCHAR(255), NAME VARCHAR(255), PWD VARCHAR(255), STUDENTID VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(38), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN_TABLE', 0)

